# Generated by Django 5.1.6 on 2025-06-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revela', '0004_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images/%y/%m/%d'),
        ),
    ]
