# Generated by Django 5.1.6 on 2025-06-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Revela', '0002_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='user',
        ),
    ]
